LeoMoriLima/ZabaFood

package-lock.json, package.json, src/app.js, src/config/index.js, src/db/postgresql.js
Added initial structure and created postgresql.js and config/index.js
=> Initial structure

src/utils/comparePassword.js
Fixed comparePassword.js, removed duplicate lines.
=> fix: fixed comparePassword.js

src/controller/loginController.js, src/repository/loginRepository.js, src/routes/loginRoutes.js, src/routes/routes.js, src/services/loginServices.js
Added loginController, loginServices, loginRepository, loginRoutes and routes
=> feat: Added login-related files

public/components/DivLogin.js, public/components/DivRegister.js
Fixed register and login fetch url
=> fix: fetch url

src/controller/productController.js, src/repository/productRepository.js, src/routes/productRoutes.js, src/routes/routes.js, src/services/productServices.js
Added product files and code : productController.js, productServices.js, productRepository.js, productRoutes.js and modified routes.js
=> feat: added product-related files: controller, services, repository and routes

src/controller/productController.js, src/repository/productRepository.js, src/routes/productRoutes.js, src/services/productServices.js
added search by name on product backend
=> feat: added search by name on product backend

src/controller/userController.js, src/repository/userRepository.js, src/services/userServices.js
Fixed verification if user exists, from controller to services
=> fix: fixed user verification from controller to services

public/components/ProductBanner.js, public/index.html, public/js/routes.js, public/pages/home.js, public/pages/login.js, public/pages/product.js, public/style.css
Added ProductBanner component to include in home page;
Changed: new font to index.html;
Changed: product endpoint in routes.js;
Changed: styles with productbanner
=> feat: Added ProductBanner.js and related necessary changes

public/components/NavFooterMain.js, public/components/NavLoginRegister.js, public/components/NavMain.js, public/components/text-a.js, public/style.css
Fixed anchos on navFooterMain.js, navLoginRegister.js, navMain.js and text-a.js
=> fix: Fixed anchors spa function

public/components/contactPage.js, public/pages/contact.js
Created contact page front on component contactPage.js. make some changes on contact.js
=> feat: Created contactPage.js

src/controller/cartController.js, src/repository/cartRepository.js, src/routes/cartRoutes.js, src/routes/routes.js, src/services/cartServices.js
Added cart-related files: controller, services, repository and routes
=> feat: added cart-related files: controller, services, repository and routes

src/controller/cartController.js, src/repository/cartRepository.js, src/routes/routes.js, src/services/cartServices.js
=> fix: some code corrections at cart-related files

src/controller/productTypeController.js, src/repository/productTypeRepository.js, src/routes/productTypeRoutes.js, src/routes/routes.js, src/services/productTypeService.js
Added productTypeController.js, productTypeService.js, productTypeRepository.js, productTypeRoutes.js;
Changed routes.js;
=> feat: Added product_type-related files: controller, service, repository and routes

src/controller/cartProductController.js, src/repository/cartProductRepository.js, src/routes/cartProductRoutes.js, src/routes/routes.js, src/services/cartProductServices.js
Added cartProductController.js
Added cartProductServices.js
Added cartProductRepository.js
Added cartProductRoutes.js
Changed routes.js
=> feat: added cart_product-related files: controller, services, repository and routes

public/components/TermsPage.js, public/js/routes.js, public/pages/terms.js
Created terms.js, TermsPage.js and created the route for /terms
=> Feat: added terms and coditions page.

public/components/AboutPage.js, public/components/ConfirmationPage.js, public/components/PolicyPage.js, public/components/TermsPage.js, public/components/contactPage.js, public/js/routes.js, public/pages/contact.js, public/pages/policy.js, public/style.css
Created policy page and fix the class on button component on some pages.
=> feat: Created Policy page

src/controller/addressController.js, src/middleware/permissionVerify.js, src/repository/addressRepository.js, src/routes/addressRoutes.js, src/routes/routes.js, src/services/addressService.js, src/services/productServices.js
Added:
- addressController.js;
- addressRepository.js;
- addressRoutes.js;
- addressService.
Changed:
- permissionVerify.js to return req.user object;
- routes.js to add address route;
- productService.js to delete console.log;
=> feat: Added address-related files: controller, service, repository and routes

src/controller/loginController.js, src/routes/loginRoutes.js
added loginCheck to loginController.js
=> feat: added loginCheck to loginController.js

src/controller/cartController.js, src/repository/cartRepository.js, src/routes/cartRoutes.js, src/services/cartServices.js
Changed:
- cartRoutes.js;
- cartController.js;
- cartService.js;
- cartRepository.js.
=> feat: Added endpoint to get cart from user_id

src/controller/addressController.js, src/repository/addressRepository.js, src/routes/addressRoutes.js, src/services/addressService.js
Changed:
- addressRoutes.js;
- addressController.js;
- addressService.js;
- addressRepository.js.
=> feat: Added endpoint to get address from user_id

public/components/MainProductCard.js, public/components/ProductMain.js, public/components/QuantityInput.js, public/pages/home.js, public/pages/product.js, public/style.css
Added:
MainProductCard.js
ProductMain.js
QuantityInput.js
product.js
Changed:
style.css
home.js
=> feat: Added product page with css and some css fixes

src/controller/creditTransactionController.js, src/repository/creditTransactionRepository.js, src/routes/creditTransactionRoutes.js, src/routes/routes.js, src/services/creditTransactionService.js
Added:
- creditTransactionRoutes.js;
- creditTransactionController.js;
- creditTransactionService.js;
- creditTransactionRepository.js;
Changed:
- routes.js - to add creditTransactionRoute.
=> feat: Added credit_transaction related files: Routes, Controller, Service and Repository

public/style.css
Changed style.css to add about page style
=> feat: Added style to about page

public/components/MainProductCard.js, public/components/ProductMain.js, public/pages/product.js, public/style.css
Changed:
MainProductCard.js
ProductMain.js
style.css
=> feat: added fetch to buttons on product page and fixed some css

public/components/CartModal.js, public/components/ProductCard.js, public/pages/cart.js
Changed:
CartModal.js
Cart.js
ProductCard.js
=> change: changed CartModal to show quantity and added header and footer to cart page

.gitignore, package-lock.json, package.json, public/components/DivRegister.js, src/controller/addressController.js, src/controller/cartController.js, src/controller/cartProductController.js, src/controller/creditTransactionController.js, src/controller/loginController.js, src/controller/productController.js, src/controller/productTypeController.js, src/controller/userController.js, src/repository/productRepository.js, src/routes/cartProductRoutes.js, src/routes/cartRoutes.js, src/routes/creditTransactionRoutes.js, src/routes/productRoutes.js, src/routes/productTypeRoutes.js, src/services/productServices.js
Added validation on controllers, on register page - frontside, and added permission verify on routes.js
=> feat: Added validation on controllers

public/components/NavMain.js, public/components/ProductCard.js, public/style.css
Changed:
- ProductCard component to load productCards even if no user logged in;
- NavMain.js and style.css to change product quantity showl logic.
=> fix: Fixed productCard load with no user login

src/repository/userRepository.js
=> change: Changed insertNewUser to create a cart to the user

public/components/ProductCardRecommended.js, public/components/ProductMain.js, public/style.css
Added:
ProductCardRecommended.js
Changed:
ProductMain.js
style.css
=> feat: Added recommended products to product page

public/components/ProductCard.js, public/style.css
Changed: 
ProductCard.js
style.css
=> feat: added redirection to the product page when clicking on the product

public/style.css
=> fix: fixed cart-page breaking height

public/components/CategoryModal.js, public/components/NavMain.js, public/style.css
Changed files : style.css, NavMain.js
New file: CategoryModal.js
=> feat: CategoryModal

src/controller/productTypeController.js, src/repository/productTypeRepository.js, src/services/productTypeService.js
Changed:
productTypeController.js
productTypeRepository.js
productTypeService.js
=> feat: added verification for inserting and updating types that already exists in product_type

public/components/HeaderMain.js, public/components/NavMain.js, public/components/ProductCard.js
Changed:
- ProductCard.js - to dispatch event when add btn clicked;
- NavMain.js - to listen event when add btn clicked and update products quantity on cart icon.
=> feat: Added dispatchEvent to update products quantity on cart icon

public/js/routes.js
=> change: Changed routes.js to a different aproach

public/components/AboutPage.js, public/components/AdminAccountPage.js, public/components/CartModal.js, public/components/CartPage.js, public/components/CategoryModal.js, public/components/CheckoutPage.js, public/components/ConfirmationPage.js, public/components/ContactPage.js, public/components/DivLogin.js, public/components/DivRegister.js, public/components/MainProductCard.js, public/components/NavFooterMain.js, public/components/NavLoginRegister.js, public/components/NavMain.js, public/components/PolicyPage.js, public/components/ProductBanner.js, public/components/ProductCard.js, public/components/ProductCardRecommended.js, public/components/TermsPage.js, public/components/Text-a.js, public/components/userAccountPage.js
Fixed every redirection to the new router approach
=> fix: fixed every redirection to the new router approach

public/js/routes.js, public/pages/about.js, public/pages/cart.js, public/pages/checkout.js, public/pages/confirmation.js, public/pages/contact.js, public/pages/home.js, public/pages/login.js, public/pages/myaccount.js, public/pages/notFound.js, public/pages/payconfirmation.js, public/pages/payment.js, public/pages/policy.js, public/pages/product.js, public/pages/products.js, public/pages/register.js, public/pages/terms.js
Added titles to the pages and added popstate event for navigation
=> feat: added titles to the pages and added popstate event for navigation

public/components/CartModal.js, public/components/CheckoutPage.js, public/components/DivRegister.js, public/components/NavMain.js, public/components/PaymentConfirmationPage.js, public/components/PaymentPage.js, public/style.css, src/controller/userController.js, src/repository/userRepository.js, src/routes/userRoutes.js, src/services/userServices.js
Changed:
- Style.css - changed checkoutpage style to avoid conflicts and standardize hovers;
- CartModal.js - included verification to only show products from cart with pending status.
- NavMain.js - included verification to only show products from cart with pending status.
- CheckoutPage.js - changed class names toa void conflict at style.css, changed freight logic to apply only on not empty carts, added total line to sum products with freight and included fetches to change pending cart to approved cart, to create new cart to user and to edit credit user balance;
- DivRegister.js - removed cnpj from cpf key;
- PaymentConfirmationPage.js - changed page redirection style;
- PaymentPage.js - changed page redirection style;
- userController.js - removed cnpj from cpf and added …
=> fix and feat: fixed some bugs and included credit_balance fetch

public/components/CartModal.js, public/style.css
Changed:
- CarTModal.js - Added addEventListener to listen dispatchEvent productAdded;
- Style.css - Fix header div plus text.
=> fix: Fixed CartModal to update when a product is added to cart

public/components/Carousel.js, public/components/CartModal.js, public/components/CategoryModal.js, public/components/NavMain.js, public/components/ProductBanner.js, public/style.css
Changed
Carousel.js
CartModal.js
CategoryModal.js
NavMain.js
ProductBanner.js
style.css
=> fix: made home page and NavMain load faster

public/components/DivLogin.js, public/components/DivRegister.js, public/components/MainProductCard.js, public/components/MessageComponent.js, public/components/MessageContainer.js, public/components/NavMain.js, public/pages/about.js, public/pages/cart.js, public/pages/checkout.js, public/pages/confirmation.js, public/pages/contact.js, public/pages/home.js, public/pages/login.js, public/pages/myaccount.js, public/pages/notFound.js, public/pages/payconfirmation.js, public/pages/payment.js, public/pages/policy.js, public/pages/product.js, public/pages/products.js, public/pages/register.js, public/pages/terms.js, public/style.css
Added
MessageComponent.js
MessageContainer.js
Changed 
style.css
/pages - added a message container for each page
=> fix and feat: Fixed some CSS issues and added a message component

public/components/MainProductSkeleton.js, public/components/ProductCardRecommendedSkeleton.js, public/components/ProductCardSkeleton.js, public/components/ProductMain.js, public/components/ProductsMain.js, public/style.css
Added
MainProductSkeleton.js
ProductCardSkeleton.js
ProductCardRecommendedSkeleton.js
Changed
style.css
ProductMain.js
ProductsMain.js
=> feat and fix: improved loading speed of product and products pages and added skeletons for product-related components

public/components/CartPage.js, public/components/CheckoutPage.js, public/components/PaymentPage.js, public/pages/payment.js, public/style.css, src/controller/cartProductController.js, src/controller/creditTransactionController.js, src/repository/userRepository.js, src/services/cartProductServices.js
CartPage.js - performance improvement;
PaymentPage.js - added validations to allow credit insert and added validations messages to users;
payment.js - Added page class to change message div style position;
userRepository.js - Changed updateUserCreditBalance query;
=> Added validations, validations messages and performance improvements

public/components/userAddressContent.js, public/style.css
Changed
style.css
userAddressContent.js
=> fix: fixed the issue with deleting images in userAddressContent and made some CSS fixes

public/components/ProductsMain.js, public/components/userAddressContent.js, public/style.css, src/controller/addressController.js
Changed
style.css
ProductsMain.js
userAddresContent.js
addressController.js
=> fix: Fixed product filtering by type, corrected user address page issues, and made some CSS enhancements

public/components/userOrdersContent.js, public/style.css, src/repository/cartRepository.js
Changed
userOrdersPage.js
cartRepository.js
style.css
=> feat: added delivered confirmation at user account page

public/components/AdminProductTypePage.js, public/style.css, src/controller/productTypeController.js, src/repository/productTypeRepository.js, src/services/productTypeService.js
Added a column url_img to product type.
Added a route to product type controller, service and repository.
Added a function to add image to the product type registration.
Added a function to edit product type image.
=> feat: Added route to add a icon image on product type

public/components/CheckoutPage.js, public/components/ProductsMain.js, public/style.css, src/controller/addressController.js, src/controller/cartController.js, src/repository/addressRepository.js, src/repository/cartRepository.js, src/services/addressService.js, src/services/cartServices.js
Changed
CheckoutPage.js - added address selection, address editing, fetch to send address_id to approved carts
style.css - new styles and fixes
addressController.js - changed getAddressByUserID
addressServices.js - changed getAddressByUserID
addressRepository.js - changed getAddressByUserID
cartController.js - changed updateCartStatus
cartServices.js - changed updateCartApproved
cartRepository.js - changed updateCartApproved
ProductsMain.js - removed console.log
=> feat: added address selection at checkout page and added adress_id to approved carts

public/components/AdminProductTypePage.js, public/components/CategoryModal.js, public/components/TypeProductBanner.js, public/index.html, src/controller/productTypeController.js, src/repository/productTypeRepository.js, src/routes/productTypeRoutes.js, src/services/productTypeService.js
Changed
TypeProductBanner.js - added images to the banner.
AdminProductTypePage.js - fixed relative paths that were causing bugs.
typeProductController.js - added getProductTypeByType.
typeProductServices.js - added getProductTypeByType.
typeProductRepository.js - changed and added getProductTypeByType.
typeProductRoutes.js - added route to getProductTypeByType.
=> feat: added image to product type related components

public/components/AdminOrderPage.js, public/components/AdminProductTypePage.js, public/components/Carousel.js, public/components/CheckoutPage.js, public/components/MainProductCard.js, public/components/userOrdersContent.js, src/repository/cartRepository.js
Changed
AdminOrderPage.js - Added custom address to each order
AdminProductTypePage.js - Fixed multiplying cards when clicked more than once in the editing modal
Carousel.js - Fixed multiplying cards when clicked more than once in the next and back buttons
CheckoutPage.js - Made complement-input accept null inputs in the editing modal
MainProductCard.js - Added loading to the buttons
userOrdersContent.js - Changed buttons text
cartRepository.js - getAllCartsByInterval now returns address infos
=> fix: fixed some issues at AdminProductTypePage and Carousel and made some refinement in general

public/components/Carousel.js, public/style.css
Changed
style.css - started media query for 1366px screen and fixed some style
Carousel.js - adjusts for responsivity
=> feat and fix: started media query in home page and fixed some style in home page

public/components/Carousel.js, public/components/CartPage.js, public/components/CheckoutPage.js, public/components/NoCreditsModal.js, public/components/QuantityInput.js, public/pages/home.js, src/repository/cartProductRepository.js, src/services/cartProductServices.js
CartPage.js - Changed logic to show discount;
QuantityInput.js - Changed minus and plus button to stay disabled while requisition is complete;
cartProductRepository.js - Changed logic to create and update cart_product with due discount;
cartProductService.js - Updated due to changes in cartProductRepository.js.
=> feat and fix: Fixed discount logic in cart_product route

public/style.css
Changed
style.css - fixed login and register page style
=> fixed: login and register page style

public/components/CartPage.js, public/components/CheckoutPage.js, public/components/MainProductCard.js, public/components/ProductCard.js, public/style.css, src/controller/cartController.js, src/repository/addressRepository.js, src/repository/cartRepository.js, src/services/cartProductServices.js
Changed
CartPage.js - Now the user cannot finish a cart with an item without stock
CheckoutPage.js - Added a message when some product has no stock
MainProductCard.js - Added stock verification on MainProductCard
ProductCard.js - Added stock verification on ProductCard
cartController.js - Added await for some functions
cartRepository.js - Fixed an error message in updateCartApproved
cartProductServices.js - Fixed price when deleting a product in the cart
=> fix: fixed some cart page, checkout page and stock related bugs

public/components/AdminAccountPage.js, public/components/AdminModifyProductPage.js, public/components/AdminOrderPage.js, public/components/CheckoutPage.js
Fixed address problem on checkout page
Fixed modify product select 
Fixed Admin order page spa reload
=> fix: fixed updated change address
